function K = controller_actsus_rajamani(A, B, ro1, ro2, ro3, ro4, ks, ms, bs)
    Q = [ks^2/ms^2+ro1, bs*ks/ms^2,    0,   -bs*ks/ms^2;...
         bs*ks/ms^2,    bs^2/ms^2+ro2, 0,   -bs^2/ms^2;...
         0,             0,             ro3, 0;...
         -bs*ks/ms^2,   -bs^2/ms^2,    0,   bs^2/ms^2+ro4];
    N = [-ks/ms^2;...
         -bs/ms^2;...
         0;
         bs/ms^2];
    R = 1/ms^2;
    K = lqr(A, B, Q, R, N);
end